name: root
channels:
    - conda-forge
dependencies:
    - numpy 
    - scipy
    - bokeh
    - autograd
    - scikit-learn
    - tensorflow
    - keras
    - ipython
    - jupyter
    - ipykernel
    - nb_conda
    - nb_conda_kernels
    - nbpresent
    - pandas
    - flask
    - geopandas
    - sqlalchemy
    - statsmodels
    - patsy
    - pip
    - pytest
    - pytest-runner
    - coverage
    - pip:
        - jsonschema
        - click
        - click-log
        - versioneer
        - pytest-coverage