name: root
channels:
    - conda-forge
dependencies:
    - numpy 
    - scipy
    - bokeh
    - autograd
    - scikit-learn
    - click
    - tensorflow
    - keras
    - h5py
    - ipython
    - jupyter
    - ipykernel
    - ipywidgets
    - nb_conda
    - nb_conda_kernels
    - pandas
    - flask
    - geopandas
    - sqlalchemy
    - statsmodels
    - patsy
    - pip
    - pytest
    - pytest-runner
    - coverage
    - pip:
        - jsonschema
        - click
        - click-log
        - tqdm
        - versioneer
        - pytest-coverage
