# Write the PowerShell $PROFILE wrapper that dot-sources the chezmoi-managed profile.
# chezmoi deploys the real config to ~/.config/powershell/profile.ps1 via template.
# $PROFILE lives in a user-specific location (e.g. OneDrive\Documents), so we write
# it here rather than trying to manage the path in chezmoi's source directory.

$managedProfile = Join-Path $HOME ".config\powershell\profile.ps1"

$wrapperContent = @"
# Generated by chezmoi - do not edit directly.
# Edit dot_config/powershell/profile.ps1.tmpl in your dotfiles repo instead.
. "$managedProfile"
"@

$profileDir = Split-Path -Parent $PROFILE
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

Set-Content -Path $PROFILE -Value $wrapperContent -Encoding UTF8
