name: root
channels:
    - conda-forge
dependencies:
    - numpy 
    - scipy
    - bokeh
    - click
    - ipython
    - jupyter
    - jupyterlab
    - ipykernel
    - ipywidgets
    - nb_conda
    - nb_conda_kernels
    - pandas
    - flask
    - geopandas
    - pip
    - pytest
    - pytest-runner
    - coverage
    - spacy
    - textacy
    - lxml
    - beautifulsoup4
    - pip:
        - jsonschema
        - click
        - click-log
        - tqdm
        - versioneer
        - pytest-coverage
