# unbind all
unbind *

# set prefix to Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config
bind r source-file -F "#{@mooks-tmux-conf}" \; display-message "Config reloaded..."

# -- pain-control keybindings --------------------------------------------------

# pane splitting
bind | split-window -h -c "#{pane_current_path}"
bind '\' split-window -fh -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -fv -c "#{pane_current_path}"

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# smaller resize increments
bind -r < resize-pane -L 1
bind -r > resize-pane -R 1

# pane swapping
bind '{' swap-pane -U
bind '}' swap-pane -D
