# -- theming ------------------------------------------------------------------
# theme name located in ~/.config/tmux/themes/
set-option -g @tmux-theme 'nord'
# enable status script for powerline-style status line parsing
set-option -g @tmux-theme-status-enable 'true'
