# list of plugins to install via tpm
# e.g.: set -g @plugin 'MunifTanjim/tmux-suspend'

# required for nord theme
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'robhurring/tmux-uptime'
