# -- init ------------------------------------------------------------------
# load main config
source-file -q "$HOME/.config/tmux/conf.d/main.conf"

# -- options ------------------------------------------------------------------
source-file -q "$HOME/.config/tmux/conf.d/options.conf"

# -- bindings ------------------------------------------------------------------
source-file -q "$HOME/.config/tmux/conf.d/bindings.conf"

# -- theming ------------------------------------------------------------------
# load theme
source-file -Fq "$HOME/.config/tmux/themes/#{@tmux-theme}.conf"

# set status via script (can be disabled with '@tmux-theme-status-enable')
run-shell "$HOME/.config/tmux/scripts/status.sh"

# -- hooks ------------------------------------------------------------------
source-file -q "$HOME/.config/tmux/conf.d/hooks.conf"

# -- plugins ------------------------------------------------------------------
# load tmux plugins (TPM is installed via chezmoi)
source-file -q "$HOME/.config/tmux/conf.d/plugins.conf"

# initialize TPM (keep this at the very bottom)
run '$HOME/.config/tmux/plugins/tpm/tpm'
