[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Chezmoi config 🏡"
path = "~/.local/share/chezmoi/"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tidal"
path = "~/"
startup_command = "~/.config/sesh/scripts/start-tidal.sh"

